// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vertr.PortfolioManager.DataAccess;

#nullable disable

namespace Vertr.Infrastructure.Pgsql.Migrations.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    partial class PortfolioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vertr.PortfolioManager.Application.Entities.OperationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<Guid?>("BookId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("JsonData")
                        .HasColumnType("json")
                        .HasColumnName("json_data");

                    b.Property<string>("JsonDataType")
                        .HasColumnType("text")
                        .HasColumnName("json_data_type");

                    b.HasKey("Id")
                        .HasName("operation_events_pkey");

                    b.ToTable("operation_events", (string)null);
                });

            modelBuilder.Entity("Vertr.PortfolioManager.Contracts.PortfolioPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric")
                        .HasColumnName("balance");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<Guid>("PortfolioSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_snapshot_id");

                    b.HasKey("Id")
                        .HasName("portfolio_positions_pkey");

                    b.HasIndex("PortfolioSnapshotId");

                    b.ToTable("portfolio_positions", (string)null);
                });

            modelBuilder.Entity("Vertr.PortfolioManager.Contracts.PortfolioSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<Guid?>("BookId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.Property<string>("JsonData")
                        .HasColumnType("json")
                        .HasColumnName("json_data");

                    b.Property<string>("JsonDataType")
                        .HasColumnType("text")
                        .HasColumnName("json_data_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("portfolio_snapshots_pkey");

                    b.ToTable("portfolio_snapshots", (string)null);
                });

            modelBuilder.Entity("Vertr.PortfolioManager.Contracts.PortfolioPosition", b =>
                {
                    b.HasOne("Vertr.PortfolioManager.Contracts.PortfolioSnapshot", null)
                        .WithMany("Positions")
                        .HasForeignKey("PortfolioSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("portfolio_position_snapshot_fk");
                });

            modelBuilder.Entity("Vertr.PortfolioManager.Contracts.PortfolioSnapshot", b =>
                {
                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
