namespace Vertr.PortfolioManager.Contracts.Extensions;

public static class TradeOperationTypeExtensions
{
    public static string GetFullName(this TradeOperationType source)
        => source switch
        {
            TradeOperationType.Unspecified => "Тип операции не определён",
            TradeOperationType.Input => "Пополнение брокерского счёта",
            TradeOperationType.BondTax => "Удержание НДФЛ по купонам",
            TradeOperationType.OutputSecurities => "Вывод ЦБ",
            TradeOperationType.Overnight => "Доход по сделке РЕПО овернайт",
            TradeOperationType.Tax => "Удержание налога",
            TradeOperationType.BondRepaymentFull => "Полное погашение облигаций",
            TradeOperationType.SellCard => "Продажа ЦБ с карты",
            TradeOperationType.DividendTax => "Удержание налога по дивидендам",
            TradeOperationType.Output => "Вывод денежных средств",
            TradeOperationType.BondRepayment => "Частичное погашение облигаций",
            TradeOperationType.TaxCorrection => "Корректировка налога",
            TradeOperationType.ServiceFee => "Удержание комиссии за обслуживание брокерского счёта",
            TradeOperationType.BenefitTax => "Удержание налога за материальную выгоду",
            TradeOperationType.MarginFee => "Удержание комиссии за непокрытую позицию",
            TradeOperationType.Buy => "Покупка ЦБ",
            TradeOperationType.BuyCard => "Покупка ЦБ с карты",
            TradeOperationType.InputSecurities => "Перевод ценных бумаг из другого депозитария",
            TradeOperationType.SellMargin => "Продажа в результате Margin-call",
            TradeOperationType.BrokerFee => "Удержание комиссии за операцию",
            TradeOperationType.BuyMargin => "Покупка в результате Margin-call",
            TradeOperationType.Dividend => "Выплата дивидендов",
            TradeOperationType.Sell => "Продажа ЦБ",
            TradeOperationType.Coupon => "Выплата купонов",
            TradeOperationType.SuccessFee => "Удержание комиссии SuccessFee",
            TradeOperationType.DividendTransfer => "Передача дивидендного дохода",
            TradeOperationType.AccruingVarmargin => "Зачисление вариационной маржи",
            TradeOperationType.WritingOffVarmargin => "Списание вариационной маржи",
            TradeOperationType.DeliveryBuy => "Покупка в рамках экспирации фьючерсного контракта",
            TradeOperationType.DeliverySell => "Продажа в рамках экспирации фьючерсного контракта",
            TradeOperationType.TrackMfee => "Комиссия за управление по счёту автоследования",
            TradeOperationType.TrackPfee => "Комиссия за результат по счёту автоследования",
            TradeOperationType.TaxProgressive => "Удержание налога по ставке 15%",
            TradeOperationType.BondTaxProgressive => "Удержание налога по купонам по ставке 15%",
            TradeOperationType.DividendTaxProgressive => "Удержание налога по дивидендам по ставке 15%",
            TradeOperationType.BenefitTaxProgressive => "Удержание налога за материальную выгоду по ставке 15%",
            TradeOperationType.TaxCorrectionProgressive => "Корректировка налога по ставке 15%",
            TradeOperationType.TaxRepoProgressive => "Удержание налога за возмещение по сделкам РЕПО по ставке 15%",
            TradeOperationType.TaxRepo => "Удержание налога за возмещение по сделкам РЕПО",
            TradeOperationType.TaxRepoHold => "Удержание налога по сделкам РЕПО",
            TradeOperationType.TaxRepoRefund => "Возврат налога по сделкам РЕПО",
            TradeOperationType.TaxRepoHoldProgressive => "Удержание налога по сделкам РЕПО по ставке 15%",
            TradeOperationType.TaxRepoRefundProgressive => "Возврат налога по сделкам РЕПО по ставке 15%",
            TradeOperationType.DivExt => "Выплата дивидендов на карту",
            TradeOperationType.TaxCorrectionCoupon => "Корректировка налога по купонам",
            TradeOperationType.CashFee => "Комиссия за валютный остаток",
            TradeOperationType.OutFee => "Комиссия за вывод валюты с брокерского счёта",
            TradeOperationType.OutStampDuty => "Гербовый сбор",
            TradeOperationType.OutputSwift => "SWIFT-перевод",
            TradeOperationType.InputSwift => "SWIFT-перевод",
            TradeOperationType.OutputAcquiring => "Перевод на карту",
            TradeOperationType.InputAcquiring => "Перевод с карты",
            TradeOperationType.OutputPenalty => "Комиссия за вывод средств",
            TradeOperationType.AdviceFee => "Списание оплаты за сервис Советов",
            TradeOperationType.TransIisBs => "Перевод ценных бумаг с ИИС на брокерский счёт",
            TradeOperationType.TransBsBs => "Перевод ценных бумаг с одного брокерского счёта на другой",
            TradeOperationType.OutMulti => "Вывод денежных средств со счёта",
            TradeOperationType.InpMulti => "Пополнение денежных средств со счёта",
            TradeOperationType.OverPlacement => "Размещение биржевого овернайта",
            TradeOperationType.OverCom => "Списание комиссии",
            TradeOperationType.OverIncome => "Доход от оверанайта",
            TradeOperationType.OptionExpiration => "Экспирация опциона",
            TradeOperationType.FutureExpiration => "Экспирация фьючерса",
            TradeOperationType.PositionOverride => "Оверрайд поизций",
            _ => "Неизвестная операция",
        };
}
