services:
  tinvest:
    build:
      context: .
      dockerfile: Dockerfile.TinvestGateway
    ports:
      - "8085:8080"
    networks:
      - vertr-infra_infra
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker 

networks:
  vertr-infra_infra:
    external: true
    driver: bridge