// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vertr.MarketData.DataAccess;

#nullable disable

namespace Vertr.Infrastructure.Pgsql.Migrations.Migrations.MarketDataDb
{
    [DbContext(typeof(MarketDataDbContext))]
    [Migration("20250807164545_MarketDataHistory")]
    partial class MarketDataHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vertr.MarketData.Contracts.Candle", b =>
                {
                    b.Property<decimal>("Close")
                        .HasColumnType("numeric")
                        .HasColumnName("close");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric")
                        .HasColumnName("high");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric")
                        .HasColumnName("low");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric")
                        .HasColumnName("open");

                    b.Property<DateTime>("TimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_utc");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasIndex("TimeUtc", "InstrumentId")
                        .IsUnique()
                        .HasDatabaseName("candles_unique");

                    b.ToTable("candles", (string)null);
                });

            modelBuilder.Entity("Vertr.MarketData.Contracts.CandleSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("disabled");

                    b.Property<string>("ExternalStatus")
                        .HasColumnType("text")
                        .HasColumnName("external_status");

                    b.Property<string>("ExternalSubscriptionId")
                        .HasColumnType("text")
                        .HasColumnName("external_subscription_id");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<int>("Interval")
                        .HasColumnType("integer")
                        .HasColumnName("interval");

                    b.Property<bool>("LoadHistory")
                        .HasColumnType("boolean")
                        .HasColumnName("load_history");

                    b.HasKey("Id")
                        .HasName("candle_subscriptions_pkey");

                    b.HasIndex("InstrumentId", "Interval")
                        .IsUnique()
                        .HasDatabaseName("candle_subscriptions_unique");

                    b.ToTable("candle_subscriptions", (string)null);
                });

            modelBuilder.Entity("Vertr.MarketData.Contracts.CandlesHistoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Count")
                        .HasColumnType("bigint")
                        .HasColumnName("count");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<int>("Interval")
                        .HasColumnType("integer")
                        .HasColumnName("interval");

                    b.HasKey("Id")
                        .HasName("candles_history_pkey");

                    b.HasIndex("InstrumentId", "Interval", "Day")
                        .IsUnique()
                        .HasDatabaseName("candles_history_unique");

                    b.ToTable("candles_history", (string)null);
                });

            modelBuilder.Entity("Vertr.MarketData.Contracts.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("InstrumentType")
                        .HasColumnType("text")
                        .HasColumnName("instrument_type");

                    b.Property<decimal?>("LotSize")
                        .HasColumnType("numeric")
                        .HasColumnName("lot_size");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.ComplexProperty<Dictionary<string, object>>("Symbol", "Vertr.MarketData.Contracts.Instrument.Symbol#Symbol", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ClassCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("symbol_class_code");

                            b1.Property<string>("Ticker")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("symbol_ticker");
                        });

                    b.HasKey("Id")
                        .HasName("instruments_pkey");

                    b.ToTable("instruments", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
