// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vertr.MarketData.DataAccess;

#nullable disable

namespace Vertr.Infrastructure.Pgsql.Migrations.Migrations.MarketDataDb
{
    [DbContext(typeof(MarketDataDbContext))]
    [Migration("20250801120108_MarketDataTables")]
    partial class MarketDataTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vertr.MarketData.Contracts.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("InstrumentKind")
                        .HasColumnType("text")
                        .HasColumnName("instrument_kind");

                    b.Property<string>("InstrumentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instrument_type");

                    b.Property<decimal?>("LotSize")
                        .HasColumnType("numeric")
                        .HasColumnName("lot_size");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.ComplexProperty<Dictionary<string, object>>("Symbol", "Vertr.MarketData.Contracts.Instrument.Symbol#Symbol", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ClassCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("symbol_class_code");

                            b1.Property<string>("Ticker")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("symbol_ticker");
                        });

                    b.HasKey("Id")
                        .HasName("instruments_pkey");

                    b.ToTable("instruments", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
