@base_address = https://localhost:7085

@account_id = f7c33024-67bc-428e-a149-e916e87e79ad
@book_id = 3fa85f64-5717-4562-b3fc-2c963f66afa6

### Последний снепшот портфеля
GET {{base_address}}/portfolio/{{account_id}}?bookId={{book_id}}

### История портфеля
GET {{base_address}}/portfolio/history/{{account_id}}?bookId={{book_id}}


### Сделать снэпшот портфеля
POST {{base_address}}/portfolio/{{account_id}}?bookId={{book_id}}
Accept: application/json
Content-Type: application/json





