@baseAddress = https://localhost:7085/api/backtests

@accountId = 93cda594-5556-44ca-8005-1c893e8d3142
@sberInstrumentId = e6123145-9665-43e0-8413-cd61b8aa9b13
@portfolioId = 6b838b7b-fb76-4621-a8db-347f70a7ace5
@backtestId = 71ca9077-7846-4445-8d69-4b92fd7b482f

### All backtests
GET {{baseAddress}}


### Backtest by Id
GET {{baseAddress}}/{{backtestId}}


### Create and run backtest 
POST {{baseAddress}}
Content-Type: application/json

  {
    "from": "2025-08-01T00:00:00Z",
    "to": "2025-08-11T00:00:00Z",
    "description": "Test backtest",
    "portfolioId": "{{portfolioId}}",
    "instrumentId": "{{sberInstrumentId}}",
    "executionState": "Created",
    "startImmediately": false
  }

### Start
PUT {{baseAddress}}/start/{{backtestId}}


### Cancel
PUT {{baseAddress}}/cancel/{{backtestId}}

