@baseAddress = https://localhost:7085/api/positions

@portfolioId = 3fa85f64-5717-4562-b3fc-2c963f66afa6
@sberInstrumentId = e6123145-9665-43e0-8413-cd61b8aa9b13

@vtbInstrumentId = 8e2b0325-0292-4654-8a18-4f63ed3b0e09

### Execute order
POST {{baseAddress}}/execute-order
Content-Type: application/json

{
  "instrumentId": "{{sberInstrumentId}}",
  "portfolioId": "{{portfolioId}}",
  "price": 310.37,
  "lots": 10
}

### Reverse
POST {{baseAddress}}/reverse
Content-Type: application/json

{
  "instrumentId": "{{sberInstrumentId}}",
  "portfolioId": "{{portfolioId}}",
  "price": 310.37
}

### Open
POST {{baseAddress}}/open
Content-Type: application/json

{
  "instrumentId": "{{sberInstrumentId}}",
  "portfolioId": "{{portfolioId}}",
  "price": 310.37,
  "lots": 10
}
