@base_address = https://localhost:7085

### Список сэндбокс акаунтов
GET {{base_address}}/tinvest/sandbox-accounts/
Accept: application/json

### Список акаунтов
GET {{base_address}}/tinvest/accounts/

### Создать акаунт
@account_name = test account 79
# @name account
POST {{base_address}}/tinvest/sandbox-account?accountName={{account_name}}
Accept: text/plain
Content-Type: application/json

### @account_id = {{account.response.body.*}}
@account_id = f7c33024-67bc-428e-a149-e916e87e79ad

### Депозит
@depo_amount = 50000
@depo_currency = RUB
PUT {{base_address}}/tinvest/sandbox-account/{{account_id}}?amount={{depo_amount}}&currency={{depo_currency}}
Accept: application/json
Content-Type: application/json

### Список операций
GET {{base_address}}/tinvest/operations/{{account_id}}
Accept: application/json

### Позиции
GET {{base_address}}/tinvest/positions/{{account_id}}
Accept: application/json

### Портфолио
GET {{base_address}}/tinvest/portfolio/{{account_id}}
Accept: application/json


### Удалить акаунт
DELETE {{base_address}}/tinvest/sandbox-account/{{account_id}}
Accept: application/json




