@base_address = https://localhost:7085

### Исторические свечи

@class_code = TQBR
@ticker = SBER
# Hour, Min_1, Min_5, Min_10, Day
@interval = Min_10
@from = 2025-06-01
@to = 2025-06-10
@limit = 100

GET {{base_address}}/tinvest/candles/{{class_code}}/{{ticker}}/{{interval}}?from={{from}}&to={{to}}&limit={{limit}}
Accept: application/json

