@base_address = https://localhost:7085

### Поиск инструмента
@query = SBER
GET {{base_address}}/tinvest/instrument-find/{{query}}
Accept: application/json

### Инструмент по тикеру
@class_code = TQBR
@ticker = SBER
GET {{base_address}}/tinvest/instrument-by-ticker/{{class_code}}/{{ticker}}
Accept: application/json

### Инструмент по Id
@rub_id = a92e2e25-a698-45cc-a781-167cf465257c
@sber_id = e6123145-9665-43e0-8413-cd61b8aa9b13
GET {{base_address}}/tinvest/instrument-by-id/{{rub_id}}
Accept: application/json

